### PR TITLE
added the same modules as the 4.4.x kernel

### PR DESCRIPTION
**Pull request by mabels**
Added the missing modules from the 4.4.x kernel fork

### CODE REVIEW

**Comment by ayufan** [comment]
Is it generated by `savedefconfig`?

**Comment by aw** [comment]
@mabels I'm not sure how you generated that list, but it seems to be missing some things.

For example:

```
# uname -r
4.4.103-rockchip-ayufan-175
# zcat /proc/config.gz | grep XFS 
CONFIG_XFS_FS=y
CONFIG_XFS_QUOTA=y
CONFIG_XFS_POSIX_ACL=y
CONFIG_XFS_RT=y
CONFIG_XFS_WARN=y
```

**Comment by mabels** [comment]
Not really. I basically added the CONFIG lines which ended with =m to that config list.

It was more about missing some Networking modules like gre.

I think we should take the raspberrypi config and transform it to an Rockchip one.
My motivation was that missed an module on Rockchip which was available on an rpi.


Meno

**Comment by ayufan** [comment]
Not sure. I usually prefer to stick to Ubuntu config. Please use `make kernel-makeconfig KERNEL_DIR=kernel-mainline`  of `linux-build` to add additional modules. It makes the config nicely organized.

**Comment by mabels** [comment]
Thats a good idea, so we should do that

Meno

**Comment by karlskewes** [comment]
Hi @mabels , Did you have time to run makeconfig per @ayufan's comment above?
Else I can do a new PR (can't push to your branch) if you prefer. Cheers

**Comment by karlskewes** [comment]
> Not sure. I usually prefer to stick to Ubuntu config. Please use `make kernel-makeconfig KERNEL_DIR=kernel-mainline` of `linux-build` to add additional modules. It makes the config nicely organized.

@ayufan : Would you be open to a new PR with the Ubuntu 18.04 LTS module list that has been through  `make kernel-makeconfig` to format up?

**Comment by ayufan** [comment]
Yes

**Pull request closed without merging**
