### PR TITLE
external: defconfig: Enable advanced routing features for WireGuard

### PR DESCRIPTION
**Pull request by ghost**
wg-quick tool in wireguard-tools package needs advanced routing to
work correctly.

This change should make it possible to use kernelspace WireGuard VPN and its tools in Ubuntu (wireguard-dkms & wireguard-tools).

### CODE REVIEW

**Comment by ayufan** [comment]
Picked

**Comment by ghost** [comment]
Tested this with `4.20.0-1083-ayufan-g686e1f1aa461` and for some reason it's not working. Maybe something has changed between 4.19-4.20 or in latest wireguard-tools. At first glance I didn't spot any relevant differences in configs. I'll make another PR when I figure this out.

**Comment by ghost** [comment]
Oy! This was my (embarrassing) fault: At some point in my testing I had removed `wireguard-dkms` package so the whole wireguard module was missing. After installing it again it works great!

So all ok for `4.20.0-1083-ayufan-g686e1f1aa461`.

**Comment by ayufan** [comment]
Great :)

**Pull request closed without merging**
